### ISSUE TITLE
Version 14.1.0.3 oci-curl issue

### ISSUE THREAD

**Issue by generic-git-user** [f5devcentral/f5-oci-failover#6]
Since upgrading to version 14.1.0.3 from version 13.1 when failing over oci-curl is throwing error:
oci-curl[22240]: curl: (6) Could not resolve host: iaas.us-phoenix-1.oraclecloud.com

DNS is working fine. Can run tgactive logged in as root and it runs fine. Can also run curl to iaas.us-phoenix-1.oraclecloud.com and it is able to connect. Ping works and resolves. Still trying to figure this one out.

**Comment by generic-git-user** [comment]
I just found that putting a host file entry resolves this issue. This makes little sense. DNS is working

**Comment by snowblind-** [comment]
This is due to changes with selinux policies in 14.x

Modifying the db variable failover.selinuxallowscripts should resolve this.

root@(localhost)(cfg-sync Standalone)(LICENSE EXPIRES IN 1 DAYS:Active)(/Common)(tmos)# modify sys db failover.selinuxallowscripts value enable
 
root@(localhost)(cfg-sync Standalone)(LICENSE EXPIRES IN 1 DAYS:Active)(/Common)(tmos)# list sys db failover.selinuxallowscripts 
sys db failover.selinuxallowscripts {
value "enable"
}

**Comment by orcuttm** [comment]
I am having the same issue on 14.1.0.2 and 15.1.0.1 even after modifying the db variable. Is there anything else that can be done besides adding a host entry or changing the SELinux from enforcing to permissive?

**Comment by snowblind-** [comment]
Can you post the result of your /var/log/messages when you initiate failover? Also, a sanitized copy of your tgactive script.
